Module2 task1
htmlacademy-adaptive/2022839-cat-energy-25 pull request #2
Opened 2022-04-23 08:42 UTC by bassilok

Разметка главной страницы

2022-04-24 14:20 UTC, pavel-nyukalo requested changes
По поводу картинок и единообразия:
1. Есть картинки с большой буквы, есть с маленькой. Надо придерживаться единообразия, и писать в одном стиле, лучше с маленькой буквы (возможно, тут придется проделать так же как я описывал в дискорде в "помощь-с-домашкой", что надо будет сначала удалить, потом залить, потом добавить в правильном формате и снова залить)
2. Есть как `-`, так и `_`, опять же надо единообразно

![image](https://user-images.githubusercontent.com/52506235/164979985-5b018fc5-a089-4456-84cb-a50a512609e1.png)

3. Пробелы надо убрать, могут возникнуть проблемы на разных платформах
![image](https://user-images.githubusercontent.com/52506235/164980110-e61c52a3-22ee-4917-8a31-45f46bfd1171.png)

4. Вот эти я думаю можно в одну `svg` объединить и экспортировать, чтобы не париться с выравниванием 
![image](https://user-images.githubusercontent.com/52506235/164980170-6127f8b5-9de0-40c0-af00-1af4157b8cba.png)

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +            <li class="site-list__item site-list__item">
Два одинаковых класса `site-list__item site-list__item`. Второй по-сути незачем, будет только засорять верстку, так что его можно убрать

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +            <li class="site-list__item site-list__item">
Тут так же

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +          <p class="main-title__subtitle">
Этот параграф не является дочерним `main-title`, соответственно не может быть его элементом. Либо другой класс ему давать, либо например от `top-info` задавать - `top-info__title` для `h1`, `top-info__subtitle` для `p` например

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +              </h2>
`h2` уже выше идет, по иерархии лучше поставить следующий уровень - `h3`

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +                <h3 class="catalog-options__link">
А здесь тогда `h4`

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +          </h1>
Не критично, но лучше стараться чтобы на странице был только один `h1`, тут можно `h2` сделать

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +              <p class="about-text">
Для каждого БЭМ-блока у нас будет свой файл стилей, здесь получится, что у нас будет файл стилей для блока `about` - `about.scss` (`about.less`) и для блока `about-text` - `about-text.scss/less`. Сейчас `about-text` у нас это отдельный БЭМ-блок, я бы предложил его сделать элементом блока `about` - `about__text`

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +              alt="Худой кот">
Пока достаточно одной картинки, адаптивные картинки будут дальше

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +          <div class="cat-slider__scale">
`cat-slider__scale` уже находится не в блоке `cat-slider` (находится рядом, а не в `div class='cat-slider'`). Надо либо поместить `cat-slider__scale` внутрь `cat-slider`, либо тут другой БЭМ-блок делать

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +      <section class="find-us__card">
Нет блока `find-us` (я бы предложил как раз вместо `find-us__card` сделать, просто убрать `__card`)

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +        <a class="main-footer__logo--cat-energy" href="index.html">
Есть модификатор, но нет того, что он модифицирует. Пример верной разметки - `about__item about__item--ingridients`. Здесь так же должно быть: сначала что модифицируем, потом модификатор

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +        </div>
Задан блок `social`, я бы предложил от него и плясать, примерно
```html
<div class='main-footer__social social'>
  <ul class='social__list'>
    <li class='social__item'>
    // и тд
</div>
```

2022-04-24 14:20 UTC, pavel-nyukalo commented on source/index.html
> +        <a class="main-footer__logo--htmlacademy" href="https://htmlacademy.ru">
Так же про модификатор

2022-04-24 20:19 UTC, bassilok commented
> 4. Вот эти я думаю можно в одну `svg` объединить и экспортировать, чтобы не париться с выравниванием
>    ![image](https://user-images.githubusercontent.com/52506235/164980170-6127f8b5-9de0-40c0-af00-1af4157b8cba.png)

я тоже так подумала, но в мобильной версии они сидят отдельно, а в других вместе, стоит их просто заменить для других версий и обьединить для этой?

2022-04-24 20:24 UTC, bassilok commented on source/index.html
> +              </h2>
заменила. опиралась на то, что по стилю одинаковые элементы

2022-04-24 20:27 UTC, bassilok commented on source/index.html
> +          </h1>
а h2 можно использовать несколько раз, если размер и стиль заголовков один или нужно каждый раз смещать на 1 пункт вниз?

2022-04-24 20:31 UTC, bassilok commented on source/index.html
> +              alt="Худой кот">
Имеешь в виду оставить в html одну, а остальные менять в css? не очень поняла как оставить в html правильно

2022-04-24 20:36 UTC, bassilok commented on source/index.html
> +          <div class="cat-slider__scale">
исправила, надеюсь правильно занесла внутрь. по идее они должны быть вместе ведь слайдер двигает картинку

2022-04-25 14:23 UTC, pavel-niukalo commented on source/index.html
> +          </h1>
Можно `h2`, как раз как заголовок секции, отлично подойдет

2022-04-25 14:26 UTC, pavel-nyukalo commented on source/index.html
> +              alt="Худой кот">
Пока оставь одну да, дальше в лекциях расскажут, как адаптивно менять

2022-04-25 14:51 UTC, pavel-nyukalo requested changes
1. ПР не прошел проверку, надо поправить (хотя при первой проверке было ок)
2. По поводу вот этой картинки, глянул макет, там можно по сути только значок академии экспортировать, а остальное текстом
![image](https://user-images.githubusercontent.com/52506235/165114258-333e2f86-062c-4540-9f0c-5e6d90727e8d.png)
3. В картинках смотри еще есть разные разделители, плюс аж три папки `favicon`, надо бы в одну папку сделать
![image](https://user-images.githubusercontent.com/52506235/165114564-930d00ec-74cb-488f-b735-90008e8a67fd.png)

2022-04-25 14:51 UTC, pavel-nyukalo commented on source/index.html
> +              <p class="about-text">
Единственное место, где остался `about-text`, ниже уже поправлено `about__text`. Тут тоже надо поправить

2022-04-25 14:51 UTC, pavel-nyukalo commented on source/index.html
> +                class="social-button social-button--twitter"
Тут получается 4 БЭМ-блока, под каждый надо будет отдельный файл препроцессорный. Предлагаю все же сделать один БЭМ-блок - `social` и от него уже задавать элементы `social__list` и тд

2022-04-25 14:51 UTC, pavel-nyukalo commented on source/index.html
> +        <a class="main-footer__logo--htmlacademy" href="https://htmlacademy.ru">
Тут не поправилось с модификатором

2022-04-25 16:31 UTC, bassilok commented on source/index.html
> +                class="social-button social-button--twitter"
поняла теперь, спасибо

2022-04-25 17:25 UTC, pavel-nyukalo approved these changes

2022-04-25 17:25 UTC, merged