Module2 task2
htmlacademy-adaptive/2022839-cat-energy-25 pull request #3
Opened 2022-04-30 01:05 UTC by bassilok

Added main layouts to catalog and form

2022-05-02 06:45 UTC, pavel-nyukalo requested changes

2022-05-02 06:45 UTC, pavel-niukalo commented on source/catalog.html
> +<!DOCTYPE html>
Тут на ПР он уже ругается верно - на пробелы
![image](https://user-images.githubusercontent.com/52506235/166190960-d396eb58-7c7e-44d9-b4fc-9438354cb757.png)

Если работаешь в VSCode, вызови черед палитру команд (ctrl + shift + P) команду "форматировать документ". Он тебе пробелы поправит

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +                Главная
Тут уже `current` не "Главная"

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +        <h1 class="catalog-title">
Не забывай, что это будет три разных файла. Не критично, но возможно при стилизации будет удобнее объединить в один файл например. `catalog__wrapper`, `catalog__title` и тд

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +          <div class="catalog-cards__item">
Тут можно списком например

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +              <span class="catalog-card__description-option">
`catalog-cardS__description` и `catalog-card__description-option`. Пропущена `S`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +              </span>
Относится ко всем `catalog-card__description-option`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +            </div>
Тут можно избавиться от половины `div` и `span` заменив это все списки определений [`dl` `dt` `dd`](https://doka.guide/html/dl-dd-dt/)

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +            </span>
Тут тоже можно сделать через список определений (например, на будущее, если вдруг сюда еще что-то добавилось бы, то ты просто добавила еще одно определение)

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +          <div class="catalog-cards__button">
Блок `catalog-extras`, а элемент `catalog-cards__button`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +        </h3>
Секциям можно `h2` давать, у нас есть один заголовок первого уровня, а дальше идут секции этой страницы, и вот им как раз `h2`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +        </h5>
Тут так же про `h2`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +          </h4>
+1

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/catalog.html
> +          <ul class="socials__list">
`social` -> `socialS__list`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +              </a>
Тут тоже `current` не "главная"

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +          <h1 class="form-title">
Тут будет 4 файла для каждого блока. Есть смысл объединить как-то

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +          <p class="form-title__text">
Этот тег не лежит внутри `form-title`, но является его элементом. Вот элементом `form-caption` он является

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +          <div class="cat-bio-wrapper">
Тоже два блока получается

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +                </p>
Копипаст с веса? Присутствуют `weight` в классе, в `name`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +              </form>
Ты закрываешь форму на трех инпутах, у нас все поля ввода должны быть внутри формы. То есть форма это почти вся страница

Получится примерно так
![image](https://user-images.githubusercontent.com/52506235/166194235-c272579c-db74-4bd1-b387-1a74fb063c31.png)

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +              <div class="line"></div>
Много лишних оберток, секций.
Будет достаточно одной формы и пять фиелдсетов внутри (как на скриншоте)

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +                  <input class="feild" type="number" id="telephone" placeholder="8 (960) 900-60-90" autocomplete="off" required>
`for` и `id` не совпадают
![image](https://user-images.githubusercontent.com/52506235/166194495-efbb3007-e5a5-4dfb-9bdb-65827939b7a7.png)

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +                <p class="field-group cat-bi__form-weight">
Пропущена `o` в `cat-bio__form-weight`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +                <h2 class="form__title">
Блок `contacts`, а элемент от блока `form` - `form__title`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +                </h2>
Аналогично

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +              <button class="button button--form" type="button">
Тут можно `type="submit"`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +            </h4>
Тут как в каталоге про секции и `h2`

2022-05-02 06:45 UTC, pavel-nyukalo commented on source/form.html
> +          <ul class="socials__list">
Аналогично с `S`

2022-05-02 21:15 UTC, bassilok commented on source/catalog.html
> +        <h1 class="catalog-title">
я просто не очень понимаю как это дальше будет видимо

2022-05-02 21:41 UTC, bassilok commented on source/catalog.html
> +          <div class="catalog-cards__button">
я так написала только потому что кнопки одинаковые. тогда наверно логичнее там убрать и сделать catalog__button везде

2022-05-02 21:50 UTC, bassilok commented on source/form.html
> +                </p>
увлеклась

2022-05-02 21:59 UTC, bassilok commented on source/form.html
> +                <h2 class="form__title">
если они одинаковые я не могу оставить им одно имя класса?

2022-05-04 16:52 UTC, pavel-nyukalo requested changes

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/catalog.html
> +<!DOCTYPE html>
Все еще ругается

![image](https://user-images.githubusercontent.com/52506235/166726750-daa750ce-e3e1-4a1d-8a00-a0e1025b0259.png)

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/catalog.html
> +          </li>
`current` все еще на "главной", мы же уже в каталоге находимся

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/catalog.html
> +          </dl>
`dl` - description list, можно один оставить, а уже внутри него `dt` - `dd`. Вот как пример с [Доки](https://doka.guide/html/dl-dd-dt/)
```html
<p>Животные героев «Гарри Поттера»</p>
<dl>
  <dt>Букля</dt>
  <dd>Полярная сова Гарри Поттера</dd>
  <dt>Живоглот</dt>
  <dd>Полукот Гермионы Грейнджер</dd>
  <dt>Пушистик</dt>
  <dd>Кролик Лаванды Браун</dd>
  <dt>Нагайна</dt>
  <dd>Змея Волан-де-Морта</dd>
</dl>
```
Один список - несколько `ключ-значение`

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/catalog.html
> +          </dl>
Дальше аналогично

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/catalog.html
> +          </div>
Нет открывающего `div`, валидатор [подскажет](https://validator.w3.org/nu/#textarea) об этом 

![image](https://user-images.githubusercontent.com/52506235/166727969-342972be-9dce-4f4f-b2a8-86a84849f72c.png)

Вот эти ошибки тоже надо поправить
![image](https://user-images.githubusercontent.com/52506235/166728083-b23fa000-4917-472d-94fc-8c17d3240aae.png)

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/form.html
> +            <li class="site-list__item site-list__item">
Два одинаковых класса, надо оставить один

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/form.html
> +          <h1 class="form__title">
Уже лучше, но смотри это элементы блока `form`, его нет, но есть блок `form-container` (это разные блоки в БЭМе), поэтому можно либо `form-container` сократить до `form`, либо у элементов прописывать `form-container__wrapper` и тд

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/form.html
> +          <section class="cat-bio">
Тут тоже, элемент `cat-bio__form` создан без блока (`cat-bio` лежит внутри элемента, получается блок внутри элемента, а должно быть наоборот - элемент внутри блока)

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/form.html
> +              <div class="cat-bio__weight">
Возможно, эти обертки будут излишни, пока можешь оставить, но как будешь строить сетки проверь - может хватит просто стилизации `fieldset`

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/form.html
> +                <h2 class="form__title">
По БЭМу нет, но если они одинаковые ты можешь вынести их в отдельный БЭМ-блок (`form-title`?) и миксовать его где надо

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/form.html
> +              <div class="line"></div>
Тоже кажется избыточным эти линии вставлять в разметку, можно будет на псевдоэлементах сделать

2022-05-04 16:52 UTC, pavel-nyukalo commented on source/form.html
> +            </div>
Можно попробовать избавиться от секций, дивов и тд. То есть у нас будет один БЭМ-блок - форма, в нем будут фиелдсеты:
```html
<form class="form">
  ...
  <fieldset class="form__fieldset">
    <legend class="form__legend">Комментарий</legend>
    ...
    // ul и тд
  </fieldset>
  ...
  <fieldset class="form__fieldset">
    <legend class="form__legend">Дополнительно</legend>
    ...
    // ul и тд
  </fieldset>
</form>
```
В таком случае у нас не будет много различных классов (а значит и файлов стилей)

2022-05-04 20:51 UTC, bassilok commented on source/form.html
> +          <h1 class="form__title">
Семен Семёныч ... вроде поняла

2022-05-04 21:01 UTC, bassilok commented on source/form.html
> +              <div class="line"></div>
я пока только такой способ нашла их прилепить, по-этому оставила так, пока это плейсхолдер, потом попробую другие способы если не получится.

2022-05-04 21:07 UTC, bassilok commented on source/form.html
> +            </div>
не очень понимаю как тут без них построить блоки

2022-05-05 05:30 UTC, pavel-nyukalo approved these changes

2022-05-05 05:30 UTC, merged