Module3 task1
htmlacademy-adaptive/2022839-cat-energy-25 pull request #4
Opened 2022-05-16 06:20 UTC by bassilok

added basic styles

2022-05-16 10:40 UTC, pavel-nyukalo requested changes

2022-05-16 10:40 UTC, pavel-niukalo commented on source/catalog.html
> +    <header class="main-header">
4 пробела стало, у нас в `editorconfig` стоит 2, так что при проверке линтер заругается

2022-05-16 10:40 UTC, pavel-niukalo commented on source/catalog.html
> +    <section class="find-us find-us__pages">
Миксовать блок и тут же его элемент нельзя - ошибка по БЭМу

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/form.html
> +      <section class="find-us find-us__pages">
Аналогично

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/index.html
> +              <section class="about__item--ingridients">
Модификатор без блока/элемента, который он модифицирует

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/index.html
> +              <section class="about__item--watersoluble">
Дальше аналогично

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/index.html
> +                  <legend class="example__statistics-box--legend">
Так же

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/base/button.less
> +.button {
`button` у нас класс, и соответственно БЭМ-блок, поэтому его лучше в папке `blocks` держать

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/about.less
> +  font-family: "Arial", sans-serif;
У `body` прописан `Arial`, поэтому здесь он наследуется, можно не писать

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/about.less
> +}
background-position: left;
background-repeat: no-repeat;

можно прописать в `about__item`, а у модификаторов менять только картинку
```css
.about__item {
  background-position: left;
  background-repeat: no-repeat;
  
  &--fast {
    // картинка
  }
}
```

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/catalog-options.less
> +}
Это должно быть в `button.less`

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/catalog.less
> +}
+1

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/contacts.less
> +.feild {
Это в `field.less`

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/example.less
> +.cat-slider__conditions {
Аналогично - в своем файле

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/main-footer.less
> +.social__list {
В своем файле

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/main-nav.less
> +.site-list__link {
+1

2022-05-16 10:40 UTC, pavel-nyukalo commented on source/less/blocks/page-body.less
> +body {
Если файл у нас `page-body`, то предлагаю здесь тоже указать не тег `body`, а класс `page-body`

2022-05-17 05:47 UTC, bassilok commented on source/index.html
> +              <section class="about__item--watersoluble">
не уверена что правильно сделала

2022-05-18 12:56 UTC, pavel-nyukalo requested changes

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/index.html
> +                <legend class="example__statistics-box--legend">
Тут смотри снова получается, что модификатор без сущности, которую он модифицирует. Но! `legend` больше похож на элемент, чем на модификатор (вопрос "что это?" - legend, элемент, модификатор отвечает на вопрос "какой?", "чем отличается?" - например, small и тд)

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/index.html
> +                <label class="example__statistics-box--text">
Аналогично с текстом

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/index.html
> +            <form class="example__statistics example__statistics-box">
В какой-то момент видимо упустил, но по сути нам тут форма не нужна. Мы данные никакие не заполняем, не отправляем. Думаю можно посмотреть в сторону других тегов

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/catalog.html
> +          class="main-header__logo-image"
Видимо, опечатка - `main-header`, а находимся в футере

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/index.html
> +              <section class="about__item about__item--ingridients">
Пока не критично, но на подумать при стилизации. Нужен ли нам тут вообще `section`?🤔 Можно будет стилизовать сразу `li`

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/less/blocks/about.less
> +  }
Это скомпилируется в `.about__item__item--fast` (`&` заменяется на выше указанный селектор, то есть на `about__item`)

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/less/blocks/button.less
> +}
Можно так же через `&` написать, но если удобнее отдельно, можешь оставить

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/less/blocks/catalog.less
> +  font-family: "Arial", sans-serif;
Наследуется, можно удалить

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/less/blocks/example.less
> +  font-family: "Arial", sans-serif;
+1

2022-05-18 12:56 UTC, pavel-nyukalo commented on source/less/blocks/main-footer.less
> +  font-family: "Arial", sans-serif;
+1

2022-05-19 14:11 UTC, bassilok commented on source/index.html
> +                <legend class="example__statistics-box--legend">
наверно поняла

2022-05-19 14:13 UTC, bassilok commented on source/index.html
> +            <form class="example__statistics example__statistics-box">
не придумала какой, что бы на рамку посадить текст, но посмотрю еще

2022-05-19 14:17 UTC, bassilok commented on source/less/blocks/about.less
> +  }
надеюсь правильно поняла...

2022-05-19 14:22 UTC, bassilok commented on source/less/blocks/about.less
> +  }
нет не так что-то. то ест мне надо прописать свойство одному а модификатором его поменять, но не вот так же?


.about__item__item--fast {
  background-image: url("../images/mobile_index/list_fast.svg");
  margin-bottom: 20px;
  background-position: left;
  background-repeat: no-repeat no-repeat;

  &--ingridients {
    background-image: url("/images/mobile_index/list_elements.svg");
  }

  &--watersoluble {
    background-image: url("../images/mobile_index/list_watersoluble.svg");
  }

  &__item--functional {
    background-image: url("../images/mobile_index/list_functional.svg");
  }
}

2022-05-23 05:20 UTC, merged